version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11@sha256:339b91052ff2f433453a963138fceb39edad08ec6398f17aaa91c34b9cf775ba

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Versions
          command: |
            node -v
            npm -v
            yarn -v
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Build
          command: yarn build

      - run:
          name: Test
          command: yarn test

      - run:
          name: Post Slack message
          command: ./bin/ci.js slack

      - run:
          name: Post GitHub message
          command: ./bin/ci.js github-post

      - run:
          name: Print env vars
          command: npx cross-ci printenv

