version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.12@sha256:2fc3cb65ca0699557c5ab804d8d41ee9a973b1cb8c4e7c57906215d040c99bfc

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Versions
          command: |
            node -v
            npm -v
            yarn -v
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Build
          command: yarn build

      - run:
          name: Test
          command: yarn test

      - run:
          name: Post Slack message
          command: ./bin/ci.js slack

      - run:
          name: Post GitHub message
          command: ./bin/ci.js github-post

      - run:
          name: Print env vars
          command: npx cross-ci printenv

