version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.15@sha256:b01f2bc6bf3df1fe7e1005f46a4bcaa3c2844f1ad361d2b34c836ddb87a58501

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Versions
          command: |
            node -v
            npm -v
            yarn -v
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Build
          command: yarn build

      - run:
          name: Test
          command: yarn test

      - run:
          name: Post Slack message
          command: ./bin/ci.js slack

      - run:
          name: Post GitHub message
          command: ./bin/ci.js github-post

      - run:
          name: Print env vars
          command: npx cross-ci printenv

